apiVersion: v1
kind: Service
metadata:
  name: {{ include "respond.fullname" . }}
  labels:
    {{- include "respond.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5555
      protocol: TCP
      name: http
  selector:
    {{- include "respond.selectorLabels" . | nindent 4 }}
