ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: respond.codes
      paths:
        - path: /
          pathType: Prefix
    - host: www.respond.codes
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: respond-tls
     hosts:
       - respond.codes
       - www.respond.codes
